steps:
- name: 'gradle:5.5.1-jdk11'
  args: ['gradle', 'build']
- name: 'gradle:5.5.1-jdk11'
  args: ['gradle', 'jib', '--image=gcr.io/$PROJECT_ID/spring-boot']
images: ['gcr.io/$PROJECT_ID/spring-boot']
